import type { RoleCode } from "@prisma/client";

export const PERMISSIONS = [
  "dashboard.read",
  "students.read",
  "students.write",
  "applicants.read",
  "applicants.write",
  "guardians.read",
  "guardians.write",
  "teachers.read",
  "teachers.write",
  "users.read",
  "users.write",
  "programs.read",
  "programs.write",
  "groups.read",
  "groups.write",
  "schedules.read",
  "schedules.write",
  "attendance.read",
  "attendance.write",
  "grades.read",
  "grades.write",
  "documents.read",
  "documents.write",
  "documents.validate",
  "finance.read",
  "finance.write",
  "cash.read",
  "cash.write",
  "collections.read",
  "collections.write",
  "scholarships.read",
  "scholarships.write",
  "marketing.read",
  "marketing.write",
  "elearning.read",
  "elearning.write",
  "communication.read",
  "communication.write",
  "calendar.read",
  "calendar.write",
  "reports.read",
  "settings.read",
  "settings.write",
  "audit.read",
  "search.read",
  "portal.student",
  "portal.guardian",
  "portal.applicant",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

const ALL_STAFF: Permission[] = PERMISSIONS.filter(
  (permission) => !permission.startsWith("portal."),
);

const ACADEMIC: Permission[] = [
  "dashboard.read",
  "students.read",
  "students.write",
  "applicants.read",
  "applicants.write",
  "guardians.read",
  "guardians.write",
  "teachers.read",
  "teachers.write",
  "programs.read",
  "programs.write",
  "groups.read",
  "groups.write",
  "schedules.read",
  "schedules.write",
  "attendance.read",
  "attendance.write",
  "grades.read",
  "grades.write",
  "documents.read",
  "documents.write",
  "documents.validate",
  "elearning.read",
  "elearning.write",
  "communication.read",
  "communication.write",
  "calendar.read",
  "calendar.write",
  "reports.read",
  "search.read",
];

export const ROLE_PERMISSIONS: Record<RoleCode, Permission[]> = {
  SUPER_ADMIN: [...PERMISSIONS],
  GENERAL_DIRECTOR: [...ALL_STAFF],
  ACADEMIC_DIRECTOR: ACADEMIC,
  SCHOOL_CONTROL: [
    "dashboard.read",
    "students.read",
    "students.write",
    "applicants.read",
    "applicants.write",
    "guardians.read",
    "guardians.write",
    "teachers.read",
    "programs.read",
    "programs.write",
    "groups.read",
    "groups.write",
    "schedules.read",
    "schedules.write",
    "attendance.read",
    "attendance.write",
    "grades.read",
    "grades.write",
    "documents.read",
    "documents.write",
    "documents.validate",
    "communication.read",
    "communication.write",
    "calendar.read",
    "calendar.write",
    "reports.read",
    "search.read",
  ],
  ADMINISTRATION: [
    "dashboard.read",
    "students.read",
    "applicants.read",
    "guardians.read",
    "guardians.write",
    "users.read",
    "documents.read",
    "documents.write",
    "communication.read",
    "communication.write",
    "calendar.read",
    "search.read",
    "settings.read",
  ],
  FINANCE: [
    "dashboard.read",
    "students.read",
    "finance.read",
    "finance.write",
    "cash.read",
    "collections.read",
    "collections.write",
    "scholarships.read",
    "scholarships.write",
    "reports.read",
    "search.read",
  ],
  CASHIER: [
    "dashboard.read",
    "students.read",
    "finance.read",
    "cash.read",
    "cash.write",
    "search.read",
  ],
  COLLECTIONS: [
    "dashboard.read",
    "students.read",
    "finance.read",
    "collections.read",
    "collections.write",
    "communication.write",
    "reports.read",
    "search.read",
  ],
  MARKETING: [
    "dashboard.read",
    "applicants.read",
    "applicants.write",
    "marketing.read",
    "marketing.write",
    "communication.write",
    "reports.read",
    "search.read",
  ],
  TEACHER: [
    "dashboard.read",
    "students.read",
    "groups.read",
    "schedules.read",
    "attendance.read",
    "attendance.write",
    "grades.read",
    "grades.write",
    "elearning.read",
    "elearning.write",
    "communication.read",
    "communication.write",
    "calendar.read",
    "search.read",
  ],
  PSYCHOPEDAGOGY: [
    "dashboard.read",
    "students.read",
    "guardians.read",
    "attendance.read",
    "grades.read",
    "documents.read",
    "communication.read",
    "communication.write",
    "calendar.read",
    "search.read",
  ],
  GUARDIAN: ["portal.guardian"],
  STUDENT: ["portal.student"],
  APPLICANT: ["portal.applicant"],
};

export function roleHasPermission(role: RoleCode, permission: Permission) {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

export function isStaffRole(role: RoleCode) {
  return !["GUARDIAN", "STUDENT", "APPLICANT"].includes(role);
}

export function defaultHome(role: RoleCode) {
  if (role === "STUDENT") return "/portal/alumno";
  if (role === "GUARDIAN") return "/portal/padres";
  if (role === "APPLICANT") return "/portal/aspirante";
  return "/app";
}
